server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/store/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery/**
    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
