server:
  port: 8082

spring:
  config:
    import: application-secret.yml
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
