server:
  port: 8081

spring:
  config:
    import: application-secret.yml
  datasource:
    url: jdbc:mysql://localhost:3306/store_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
